nome1 = input("Digite o nome do produto 1: ")
preco1 = float(input("Digite o preço do produto 1: "))
quantidade1 = int(input("Digite a quantidade do produto 1: "))
nome2 = input("Digite o nome do produto 2: ")
preco2 = float(input("Digite o preço do produto 2: "))
quantidade2 = int(input("Digite a quantidade do produto 2: "))
nome3 = input("Digite o nome do produto 3: ")
preco3 = float(input("Digite o preço do produto 3: "))
quantidade3 = int(input("Digite a quantidade do produto 3: "))
valor_total = (preco3*quantidade3)+(preco2*quantidade2)+(preco1*quantidade1)
print(f"Total: R${valor_total:,.2f}")